FROM debian:stable
ENV https_proxy=http://100.78.104.201:8001
ENV http_proxy=http://100.78.104.201:8001
RUN echo "deb-src http://deb.debian.org/debian buster main contrib non-free" >> /etc/apt/sources.list \
&& apt update \
&& apt update \
&& apt-get -y upgrade \
&& apt install --no-install-recommends --no-install-suggests -y curl unzip base-files automake base-passwd pkg-config bash coreutils debianutils diffutils dpkg e2fsprogs findutils grep gzip hostname ncurses-base tar git bsdutils \
&& dpkg --add-architecture armhf \
&& apt-get update \
&& apt-get install -y build-essential crossbuild-essential-armhf \
&& apt-get build-dep -y -a armhf e2guardian \
&& git clone https://github.com/raspberrypi/tools.git --depth 1 /tmp/tools 
#&& PATH=/tmp/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin:${PATH}
RUN git clone https://github.com/e2guardian/e2guardian.git /builds/fredbcode/e2guardian \ 
&& cd /builds/fredbcode/e2guardian \
&& ./autogen.sh \
&& export \
&& ./configure --host=arm-linux-gnueabihf --prefix=/usr --enable-clamd=yes --with-proxyuser=e2guardian --with-proxygroup=e2guardian --sysconfdir=/etc --localstatedir=/var --enable-icap=yes --enable-commandline=yes --enable-email=yes --enable-ntlm=yes --enable-pcre=yes --enable-sslmitm=yes \
&& make ARCH=arm-linux-gnueabihf 
RUN file src/e2guardian \ 
&& make clean 
