#! /bin/sh -e

init_failed ()
{
        echo "WARNING: Stopping e2guardian failed! Upgrade or removal may be incomplete!" 
}

# Automatically added by dh_installinit
if [ -x "/etc/init.d/e2guardian" ]; then
	invoke-rc.d e2guardian stop || init_failed
fi
if [ -d /run/systemd/system ] ; then
        systemctl stop e2guardian
fi
# End automatically added section

